import { Thelayout } from "@/components/TheLayout"
import type { Metadata } from "next"
import { Providers } from "./provider"
import AuthProvider from "./session"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider>
            <Thelayout>{children}</Thelayout>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  )
}
