import { Thelayout } from "@/components/TheLayout";
import { connect } from "@/lib/db";
import type { Metadata } from "next";
import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  connect();

  return (
    <html lang="en">
      <body>
        <Providers>
          <Thelayout>{children}</Thelayout>
        </Providers>
      </body>
    </html>
  );
}
